[project]
name = "jrit"
repo = "Ssentiago/jrit"
branches = ["main"]
changelog_type = "conventional"
changelog = "CHANGELOG.md"
release_mode = "ci"

[[components]]
name = "jrit"
path = "."
build = ""
artifact = ""
zip = false

[[components.version_files]]
file = "Cargo.toml"